name: Style Dictionary Build

on:
  push:
    branches:
      - main
      - css-json  # Add your branch name here
    paths:
      - 'colors.tokens.json'
      - 'config.json'
      - 'css-imports/variables.scss'
      - 'css-imports/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install


      - name: Convert SCSS to JSON
        run: node scss-to-json.js css-imports/variables.scss build/variables.json

      - name: Post-process JSON
        run: node post-process-json.js

      - name: Commit and push JSON changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build/variables.json
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Convert SCSS to JSON"
            git push